name: barchaos

channels:
  - astropy

dependencies:
  - python=3
  - astropy>=2
  - numpy
  - cython
  - matplotlib
  - scipy
  - jupyter
  - notebook
  - h5py
  - pip:
    - git+https://github.com/adrn/gala
    - git+https://github.com/adrn/superfreq
    - schwimmbad
    - mpi4py
    - ruamel.yaml
